name: Build and Push Springboot app to docker

on:
  push:
  pull_request:
    branches:
      - main
    
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Scan credentials
        uses: outscale-dev/cred-scan@main
        with:
          scan_path: "./"

      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml
        
      - name: Test app
        if: github.event_name == 'pull_request'
        run: mvn -B test --file pom.xml